-- Prog 63: ocultar ligas prueba + actualizar a últimos datos oficiales
-- Fuente: TercerTiempo_web/public/programas/63/resultados.html
-- Primera A: J-38 (5 en cancha + 4 defaults + 1 pendiente) + tabla oficial J-38 + cuartos definidos
-- Especial: torneo nuevo J-5 (8 jugados + 1 pendiente), nuevos equipos Galaxi y Juárez FC

-- 0. Ocultar ligas de prueba
update public.leagues set is_public = false, status = 'inactive', updated_at = now()
where slug in ('liga-municipal-perote', 'liga-qa-codex');

-- 1. Especial: cerrar torneo anterior, abrir torneo actual J-5
update public.seasons set status = 'completed'
where id in (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026');

insert into public.seasons (league_id, name, slug, start_date, end_date, status)
values ((select id from public.leagues where slug='primera-fuerza-especial'), 'Torneo Actual 2026 · J-5', 'torneo-actual-2026', '2026-09-01', '2026-12-31', 'active')
on conflict (league_id, slug) do update set name=excluded.name, status='active';

-- 1b. Nuevos equipos Especial (Galaxi, Juárez FC)
insert into public.teams (league_id, name, slug, status) values
  ((select id from public.leagues where slug='primera-fuerza-especial'), 'Galaxi', 'galaxi', 'active'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), 'Juárez FC', 'juarez-fc', 'active')
on conflict (league_id, slug) do update set name=excluded.name, status='active';

-- 1c. Partidos Especial J-5 (torneo-actual-2026)
delete from public.matches
where season_id = (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='torneo-actual-2026')
  and round_name = 'Jornada 5';

insert into public.matches (league_id, season_id, home_team_id, away_team_id, scheduled_at, status, home_score, away_score, round_name, stage, leg) values
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='torneo-actual-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='sor-juana'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='rangers'), '2026-09-13T12:00:00-06:00', 'completed', 4, 2, 'Jornada 5', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='torneo-actual-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='guerreros-fc'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='galaxi'), '2026-09-13T12:00:00-06:00', 'completed', 0, 2, 'Jornada 5', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='torneo-actual-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='real-victoria'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='manchester'), '2026-09-13T12:00:00-06:00', 'completed', 2, 0, 'Jornada 5', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='torneo-actual-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='red-bull'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='aferrados'), '2026-09-13T12:00:00-06:00', 'completed', 3, 2, 'Jornada 5', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='torneo-actual-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='halcones'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='sabinal'), '2026-09-13T12:00:00-06:00', 'completed', 3, 2, 'Jornada 5', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='torneo-actual-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='bads'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='juarez-fc'), '2026-09-13T12:00:00-06:00', 'completed', 5, 4, 'Jornada 5', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='torneo-actual-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='arsenal'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='pinochos'), '2026-09-13T12:00:00-06:00', 'completed', 1, 2, 'Jornada 5', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='torneo-actual-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='micheleros'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='molinos'), '2026-09-13T12:00:00-06:00', 'completed', 1, 1, 'Jornada 5', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='torneo-actual-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='liverpool'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='tiburones'), '2026-09-13T12:00:00-06:00', 'scheduled', 0, 0, 'Jornada 5', 'regular_season', 'single');

-- 2. Primera A J-38 (misma temporada-2026): resultados en cancha
delete from public.matches
where season_id = (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026')
  and round_name like 'Jornada 38%';

insert into public.matches (league_id, season_id, home_team_id, away_team_id, scheduled_at, status, home_score, away_score, round_name, stage, leg) values
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='perris-fc'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='pumas'), '2026-09-14T12:00:00-06:00', 'completed', 0, 1, 'Jornada 38', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='warners'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='boca-jr'), '2026-09-14T12:00:00-06:00', 'completed', 0, 2, 'Jornada 38', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='molinos'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='racing'), '2026-09-14T12:00:00-06:00', 'completed', 5, 3, 'Jornada 38', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='coyotes-neza'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='mi-barrio'), '2026-09-14T12:00:00-06:00', 'completed', 1, 5, 'Jornada 38', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='dep-jardin'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='psg'), '2026-09-14T12:00:00-06:00', 'completed', 4, 3, 'Jornada 38', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='viveros'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='pescados'), '2026-09-14T12:00:00-06:00', 'scheduled', 0, 0, 'Jornada 38', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='everton'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='barrio-unido'), '2026-09-14T12:00:00-06:00', 'completed', 2, 0, 'Jornada 38 - Default', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='cuervos'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='halcones'), '2026-09-14T12:00:00-06:00', 'completed', 2, 0, 'Jornada 38 - Default', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='correcaminos'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='river-plate'), '2026-09-14T12:00:00-06:00', 'completed', 2, 0, 'Jornada 38 - Default', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='atletico-libertad'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='vaper'), '2026-09-14T12:00:00-06:00', 'completed', 2, 0, 'Jornada 38 - Default', 'regular_season', 'single');

-- 2b. Cuartos Primera A definidos (horarios pendientes -> scheduled)
delete from public.matches
where season_id = (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026')
  and stage = 'quarter_finals';

insert into public.matches (league_id, season_id, home_team_id, away_team_id, scheduled_at, status, home_score, away_score, round_name, stage, leg, series_id) values
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='everton'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='molinos'), '2026-09-20T12:00:00-06:00', 'scheduled', 0, 0, 'Cuartos de final', 'quarter_finals', 'single', 'QA1'),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='perris-fc'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='correcaminos'), '2026-09-20T12:00:00-06:00', 'scheduled', 0, 0, 'Cuartos de final', 'quarter_finals', 'single', 'QA2'),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='psg'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='mi-barrio'), '2026-09-20T12:00:00-06:00', 'scheduled', 0, 0, 'Cuartos de final', 'quarter_finals', 'single', 'QA3'),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='pumas'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='cuervos'), '2026-09-20T12:00:00-06:00', 'scheduled', 0, 0, 'Cuartos de final', 'quarter_finals', 'single', 'QA4');

-- 3. Standings oficiales Primera A J-38 (upsert post-trigger)
insert into public.standings (league_id, season_id, team_id, played, won, drawn, lost, goals_for, goals_against, goal_difference, points)
values
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='everton'), 38, 27, 1, 10, 67, 12, 55, 82),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='perris-fc'), 38, 25, 3, 10, 53, 12, 41, 78),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='psg'), 38, 24, 2, 12, 40, 12, 28, 74),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='pumas'), 38, 21, 3, 14, 26, 12, 14, 66),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='cuervos'), 38, 21, 3, 14, 21, 12, 9, 66),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='mi-barrio'), 38, 20, 4, 14, 12, 12, 0, 64),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='correcaminos'), 38, 20, 3, 15, 27, 12, 15, 63),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='molinos'), 38, 20, 2, 16, 31, 12, 19, 62),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='boca-jr'), 38, 20, 1, 17, 33, 12, 21, 61),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='racing'), 38, 18, 3, 17, 20, 12, 8, 57),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='coyotes-neza'), 38, 16, 2, 20, 12, 45, -33, 50),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='warners'), 38, 14, 3, 21, 12, 18, -6, 45),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='pescados'), 38, 15, 2, 21, 12, 13, -1, 47),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='barrio-unido'), 38, 12, 4, 22, 12, 12, 0, 40),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='atletico-libertad'), 38, 16, 1, 21, 12, 12, 0, 49),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='dep-jardin'), 38, 11, 3, 24, 12, 12, 0, 36),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='viveros'), 37, 7, 2, 28, 12, 12, 0, 23),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='river-plate'), 0, 0, 0, 0, 0, 0, 0, 0),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='halcones'), 0, 0, 0, 0, 0, 0, 0, 0),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='vaper'), 0, 0, 0, 0, 0, 0, 0, 0)
on conflict (season_id, team_id) do update set
  played=excluded.played, won=excluded.won, drawn=excluded.drawn, lost=excluded.lost,
  goals_for=excluded.goals_for, goals_against=excluded.goals_against,
  goal_difference=excluded.goal_difference, points=excluded.points, updated_at=now();

-- 4. Actualizar descripción ligas a estado Prog63
update public.leagues set description='Liga Luis Pirata Fuente · Torneo Actual 2026 · Jornada 5 (Prog 63)', updated_at=now() where slug='primera-fuerza-especial';
update public.leagues set description='Temporada 2026 · Tabla oficial J-38 + Cuartos definidos (Prog 63)', updated_at=now() where slug='primera-a';
