-- Migración: Seed Tercer Tiempo web -> FutPro Manager
-- Ligas: Primera Fuerza Especial (Liga Luis Pirata Fuente) y Primera A Temporada 2026
-- Fuente: TercerTiempo_web/src/data/quarterfinals.js, primeraA.js, resultados_primera_fuerza_especial.json
-- Nota: standings oficiales solo traen Pts/Dif/JJ, sin W/D/L/GF/GA detallados.
-- Se preservan Pts/Dif/JJ oficiales y se estima desglose W/D/L/GF/GA válido para constraints.
-- Los partidos cargados (J17, Cuartos ida/vuelta, J29) disparan el trigger de recálculo;
-- por eso al final se hace upsert de standings oficiales para monitoreo.

-- 0. Ligas
insert into public.leagues (name, slug, description, region, city, state, country, is_public, status, created_by)
values
  ('Primera Fuerza Especial', 'primera-fuerza-especial', 'Liga Luis Pirata Fuente · Tras J-17 · Cuartos de final (ida y vuelta)', 'Perote, Veracruz', 'Perote', 'Veracruz', 'Mexico', true, 'active', 'a37100ec-d8cd-4a46-bca4-49f86e1cade6'),
  ('Primera A', 'primera-a', 'Temporada 2026 · Jornada 29', 'Perote, Veracruz', 'Perote', 'Veracruz', 'Mexico', true, 'active', 'a37100ec-d8cd-4a46-bca4-49f86e1cade6')
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  is_public = excluded.is_public,
  status = excluded.status,
  updated_at = now();

-- 1. Temporadas 2026
insert into public.seasons (league_id, name, slug, start_date, end_date, status)
values
  ((select id from public.leagues where slug='primera-fuerza-especial'), 'Temporada 2026', 'temporada-2026', '2026-01-01', '2026-12-31', 'active'),
  ((select id from public.leagues where slug='primera-a'), 'Temporada 2026', 'temporada-2026', '2026-01-01', '2026-12-31', 'active')
on conflict (league_id, slug) do update set
  name = excluded.name, start_date = excluded.start_date, end_date = excluded.end_date, status = excluded.status;

-- 2. Equipos Primera Fuerza Especial (18, nombres normalizados)
insert into public.teams (league_id, name, slug, status) values
  ((select id from public.leagues where slug='primera-fuerza-especial'), 'Molinos', 'molinos', 'active'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), 'Halcones', 'halcones', 'active'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), 'Red Bull', 'red-bull', 'active'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), 'Liverpool', 'liverpool', 'active'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), 'Arsenal', 'arsenal', 'active'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), 'Ranger''s', 'rangers', 'active'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), 'Sabinal', 'sabinal', 'active'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), 'Micheleros', 'micheleros', 'active'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), 'Real Victoria', 'real-victoria', 'active'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), 'Sor Juana', 'sor-juana', 'active'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), 'Felinos', 'felinos', 'active'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), 'Unión Victoria', 'union-victoria', 'active'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), 'Manchester', 'manchester', 'active'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), 'Aferrados', 'aferrados', 'active'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), 'Pinochos', 'pinochos', 'active'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), 'Guerreros FC', 'guerreros-fc', 'active'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), 'Bad''s', 'bads', 'active'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), 'Tiburones', 'tiburones', 'active')
on conflict (league_id, slug) do update set name = excluded.name, status='active';

-- 3. Equipos Primera A (20)
insert into public.teams (league_id, name, slug, status) values
  ((select id from public.leagues where slug='primera-a'), 'PSG', 'psg', 'active'),
  ((select id from public.leagues where slug='primera-a'), 'Perris FC', 'perris-fc', 'active'),
  ((select id from public.leagues where slug='primera-a'), 'Everton', 'everton', 'active'),
  ((select id from public.leagues where slug='primera-a'), 'Pumas', 'pumas', 'active'),
  ((select id from public.leagues where slug='primera-a'), 'Cuervos', 'cuervos', 'active'),
  ((select id from public.leagues where slug='primera-a'), 'River Plate', 'river-plate', 'active'),
  ((select id from public.leagues where slug='primera-a'), 'Racing', 'racing', 'active'),
  ((select id from public.leagues where slug='primera-a'), 'Boca Jr', 'boca-jr', 'active'),
  ((select id from public.leagues where slug='primera-a'), 'Halcones', 'halcones', 'active'),
  ((select id from public.leagues where slug='primera-a'), 'Mi Barrio', 'mi-barrio', 'active'),
  ((select id from public.leagues where slug='primera-a'), 'Molinos', 'molinos', 'active'),
  ((select id from public.leagues where slug='primera-a'), 'Correcaminos', 'correcaminos', 'active'),
  ((select id from public.leagues where slug='primera-a'), 'Coyotes Neza', 'coyotes-neza', 'active'),
  ((select id from public.leagues where slug='primera-a'), 'Pescados', 'pescados', 'active'),
  ((select id from public.leagues where slug='primera-a'), 'Warners', 'warners', 'active'),
  ((select id from public.leagues where slug='primera-a'), 'Dep. Jardín', 'dep-jardin', 'active'),
  ((select id from public.leagues where slug='primera-a'), 'Atlético Libertad', 'atletico-libertad', 'active'),
  ((select id from public.leagues where slug='primera-a'), 'Barrio Unido', 'barrio-unido', 'active'),
  ((select id from public.leagues where slug='primera-a'), 'Viveros', 'viveros', 'active'),
  ((select id from public.leagues where slug='primera-a'), 'Vaper', 'vaper', 'active')
on conflict (league_id, slug) do update set name = excluded.name, status='active';

-- 4. Sedes (cuartos ida)
insert into public.venues (league_id, name, city, state) values
  ((select id from public.leagues where slug='primera-fuerza-especial'), 'Bachiller', 'Perote', 'Veracruz'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), 'Sabinal', 'Perote', 'Veracruz'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), 'Libertad', 'Perote', 'Veracruz'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), 'Fco. I Madero', 'Perote', 'Veracruz'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), 'Campo Municipal', 'Perote', 'Veracruz'),
  ((select id from public.leagues where slug='primera-a'), 'Campo Municipal', 'Perote', 'Veracruz')
on conflict do nothing;

-- 5. Partidos J17 Primera Fuerza Especial (regular_season, completed)
-- Uso equipo_id via subselect por slug para idempotencia: se borran e insertan los de round J-17 para evitar duplicados.
delete from public.matches
where season_id = (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026')
  and round_name = 'Jornada 17';

insert into public.matches (league_id, season_id, home_team_id, away_team_id, scheduled_at, status, home_score, away_score, round_name, stage, leg) values
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='halcones'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='micheleros'), '2026-08-23T12:00:00-06:00', 'completed', 3, 2, 'Jornada 17', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='liverpool'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='rangers'), '2026-08-23T12:00:00-06:00', 'completed', 2, 1, 'Jornada 17', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='guerreros-fc'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='sabinal'), '2026-08-23T12:00:00-06:00', 'completed', 1, 3, 'Jornada 17', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='real-victoria'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='pinochos'), '2026-08-23T12:00:00-06:00', 'completed', 1, 4, 'Jornada 17', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='red-bull'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='sor-juana'), '2026-08-23T12:00:00-06:00', 'completed', 2, 0, 'Jornada 17', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='arsenal'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='union-victoria'), '2026-08-23T12:00:00-06:00', 'completed', 3, 0, 'Jornada 17', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='manchester'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='molinos'), '2026-08-23T12:00:00-06:00', 'completed', 0, 3, 'Jornada 17', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='bads'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='tiburones'), '2026-08-23T12:00:00-06:00', 'completed', 2, 3, 'Jornada 17', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='felinos'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='aferrados'), '2026-08-23T12:00:00-06:00', 'completed', 1, 0, 'Jornada 17', 'regular_season', 'single');

-- 6. Cuartos de final ida/vuelta (quarter_finals)
delete from public.matches
where season_id = (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026')
  and stage = 'quarter_finals';

insert into public.matches (league_id, season_id, home_team_id, away_team_id, scheduled_at, status, home_score, away_score, round_name, stage, leg, series_id) values
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='molinos'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='micheleros'), '2026-08-30T12:00:00-06:00', 'completed', 3, 0, 'Cuartos de final - Ida', 'quarter_finals', 'first_leg', 'CF1'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='molinos'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='micheleros'), '2026-09-06T12:00:00-06:00', 'completed', 1, 0, 'Cuartos de final - Vuelta', 'quarter_finals', 'second_leg', 'CF1'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='halcones'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='sabinal'), '2026-08-30T10:00:00-06:00', 'completed', 1, 2, 'Cuartos de final - Ida', 'quarter_finals', 'first_leg', 'CF2'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='halcones'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='sabinal'), '2026-09-06T10:00:00-06:00', 'completed', 2, 1, 'Cuartos de final - Vuelta', 'quarter_finals', 'second_leg', 'CF2'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='red-bull'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='rangers'), '2026-08-30T08:00:00-06:00', 'completed', 2, 1, 'Cuartos de final - Ida', 'quarter_finals', 'first_leg', 'CF3'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='red-bull'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='rangers'), '2026-09-06T08:00:00-06:00', 'completed', 4, 2, 'Cuartos de final - Vuelta', 'quarter_finals', 'second_leg', 'CF3'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='liverpool'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='arsenal'), '2026-08-30T08:00:00-06:00', 'completed', 1, 2, 'Cuartos de final - Ida', 'quarter_finals', 'first_leg', 'CF4'),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='liverpool'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='arsenal'), '2026-09-06T08:00:00-06:00', 'completed', 0, 1, 'Cuartos de final - Vuelta', 'quarter_finals', 'second_leg', 'CF4');

-- 7. Partidos J29 Primera A
delete from public.matches
where season_id = (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026')
  and round_name like 'Jornada 29%';

insert into public.matches (league_id, season_id, home_team_id, away_team_id, scheduled_at, status, home_score, away_score, round_name, stage, leg) values
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='perris-fc'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='dep-jardin'), '2026-09-07T12:00:00-06:00', 'completed', 4, 0, 'Jornada 29', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='atletico-libertad'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='racing'), '2026-09-07T12:00:00-06:00', 'completed', 2, 1, 'Jornada 29', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='cuervos'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='correcaminos'), '2026-09-07T12:00:00-06:00', 'completed', 3, 0, 'Jornada 29', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='molinos'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='mi-barrio'), '2026-09-07T12:00:00-06:00', 'completed', 3, 1, 'Jornada 29', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='psg'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='coyotes-neza'), '2026-09-07T12:00:00-06:00', 'completed', 6, 5, 'Jornada 29', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='pumas'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='pescados'), '2026-09-07T12:00:00-06:00', 'completed', 4, 2, 'Jornada 29', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='boca-jr'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='barrio-unido'), '2026-09-07T12:00:00-06:00', 'completed', 4, 1, 'Jornada 29', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='warners'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='river-plate'), '2026-09-07T12:00:00-06:00', 'completed', 2, 0, 'Jornada 29 - Administrativo', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='viveros'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='halcones'), '2026-09-07T12:00:00-06:00', 'completed', 2, 0, 'Jornada 29 - Administrativo', 'regular_season', 'single'),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='everton'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='vaper'), '2026-09-07T12:00:00-06:00', 'completed', 2, 0, 'Jornada 29 - Administrativo', 'regular_season', 'single');

-- 8. Standings oficiales (upsert post-trigger para monitoreo)
-- Especial J17: played 17, pts/dif oficiales
insert into public.standings (league_id, season_id, team_id, played, won, drawn, lost, goals_for, goals_against, goal_difference, points)
values
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='molinos'), 17, 14, 2, 1, 52, 12, 40, 44),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='halcones'), 17, 14, 0, 3, 48, 12, 36, 42),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='red-bull'), 17, 12, 1, 4, 43, 12, 31, 37),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='liverpool'), 17, 12, 1, 4, 35, 12, 23, 37),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='arsenal'), 17, 10, 2, 5, 26, 12, 14, 32),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='rangers'), 17, 10, 1, 6, 25, 12, 13, 31),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='sabinal'), 17, 10, 0, 7, 27, 12, 15, 30),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='micheleros'), 17, 9, 2, 6, 20, 12, 8, 29),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='real-victoria'), 17, 7, 2, 8, 12, 16, -4, 23),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='sor-juana'), 17, 7, 1, 9, 17, 12, 5, 22),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='felinos'), 17, 6, 0, 11, 12, 25, -13, 18),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='union-victoria'), 17, 5, 2, 10, 12, 34, -22, 17),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='manchester'), 17, 5, 2, 10, 12, 23, -11, 17),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='aferrados'), 17, 5, 0, 12, 12, 18, -6, 15),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='pinochos'), 17, 4, 1, 12, 12, 38, -26, 13),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='guerreros-fc'), 17, 3, 1, 13, 12, 36, -24, 10),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='bads'), 17, 3, 1, 13, 12, 42, -30, 10),
  ((select id from public.leagues where slug='primera-fuerza-especial'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-fuerza-especial' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-fuerza-especial' and t.slug='tiburones'), 17, 3, 0, 14, 12, 42, -30, 9)
on conflict (season_id, team_id) do update set
  played=excluded.played, won=excluded.won, drawn=excluded.drawn, lost=excluded.lost,
  goals_for=excluded.goals_for, goals_against=excluded.goals_against,
  goal_difference=excluded.goal_difference, points=excluded.points, updated_at=now();

-- Primera A pre-J29: JJ/Dif/Pts oficiales
insert into public.standings (league_id, season_id, team_id, played, won, drawn, lost, goals_for, goals_against, goal_difference, points)
values
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='psg'), 27, 19, 1, 7, 43, 12, 31, 58),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='perris-fc'), 26, 18, 2, 6, 51, 12, 39, 56),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='everton'), 26, 17, 0, 9, 47, 12, 35, 51),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='pumas'), 26, 14, 2, 10, 25, 12, 13, 44),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='cuervos'), 27, 14, 1, 12, 12, 15, -3, 43),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='river-plate'), 26, 14, 0, 12, 22, 12, 10, 42),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='racing'), 27, 13, 2, 12, 22, 12, 10, 41),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='boca-jr'), 27, 13, 1, 13, 29, 12, 17, 40),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='halcones'), 27, 13, 1, 13, 12, 23, -11, 40),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='mi-barrio'), 27, 13, 1, 13, 12, 24, -12, 40),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='molinos'), 27, 12, 2, 13, 13, 12, 1, 38),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='correcaminos'), 27, 12, 2, 13, 12, 14, -2, 38),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='coyotes-neza'), 27, 12, 1, 14, 12, 31, -19, 37),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='pescados'), 27, 11, 2, 14, 12, 22, -10, 35),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='warners'), 27, 10, 2, 15, 12, 12, 0, 32),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='dep-jardin'), 27, 9, 0, 18, 12, 12, 0, 27),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='atletico-libertad'), 27, 9, 0, 18, 12, 12, 0, 27),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='barrio-unido'), 27, 8, 2, 17, 12, 12, 0, 26),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='viveros'), 27, 5, 2, 20, 12, 12, 0, 17),
  ((select id from public.leagues where slug='primera-a'), (select s.id from public.seasons s join public.leagues l on l.id=s.league_id where l.slug='primera-a' and s.slug='temporada-2026'), (select t.id from public.teams t join public.leagues l on l.id=t.league_id where l.slug='primera-a' and t.slug='vaper'), 27, 0, 0, 27, 10, 10, 0, 0)
on conflict (season_id, team_id) do update set
  played=excluded.played, won=excluded.won, drawn=excluded.drawn, lost=excluded.lost,
  goals_for=excluded.goals_for, goals_against=excluded.goals_against,
  goal_difference=excluded.goal_difference, points=excluded.points, updated_at=now();
